name: Release

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    name: Create a release
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - uses: brpaz/action-semantic-release@v1
        with:
          branch: main
          install_plugins: "semantic-release-exec"
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}